name: "reviewdog"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: Run reviewdog
      env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet
